<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WIN-K344N9L8257" name="testScripts.TWITTER.TC_11_GET_Twitter_oAuth_Latest_Tweet" tests="1" failures="1" timestamp="31 Jul 2018 11:58:31 GMT" time="4.238" errors="0">
  <testcase name="runTC_11_GET_Twitter_oAuth_Latest_Tweet" time="4.238" classname="testScripts.TWITTER.TC_11_GET_Twitter_oAuth_Latest_Tweet">
    <failure type="java.lang.AssertionError" message="Exception other than UI validation. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception other than UI validation. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at supportLiberaries.DriverScript.triggerExecution(DriverScript.java:63)
at supportLiberaries.DriverScript.startExecution(DriverScript.java:30)
at testScripts.TWITTER.TC_11_GET_Twitter_oAuth_Latest_Tweet.runTC_11_GET_Twitter_oAuth_Latest_Tweet(TC_11_GET_Twitter_oAuth_Latest_Tweet.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- runTC_11_GET_Twitter_oAuth_Latest_Tweet -->
</testsuite> <!-- testScripts.TWITTER.TC_11_GET_Twitter_oAuth_Latest_Tweet -->
