<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="WIN-K344N9L8257" name="testScripts.BASIC_SANITY_TEST.TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login" tests="2" failures="0" timestamp="23 Aug 2018 14:00:18 GMT" time="0.247" errors="1">
  <testcase name="setScriptHelper" time="0.247" classname="testScripts.BASIC_SANITY_TEST.TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at supportLiberaries.TestCaseBase.setScriptHelper(TestCaseBase.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setScriptHelper -->
  <testcase name="Testing_TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login" time="0.000" classname="testScripts.BASIC_SANITY_TEST.TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login">
    <skipped/>
  </testcase> <!-- Testing_TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login -->
</testsuite> <!-- testScripts.BASIC_SANITY_TEST.TC03_Sanity_Test_For_SIGMA_CPQ_Salesforce_Website_Login -->
